# Site settings
title: Matthew DeAbreu
email: Matthew.DeAbreu@gmail.com
description: My personal website and blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mdeabreu.com" # the base hostname & protocol for your site

# Author
author:
  name: Matthew DeAbreu
  url: http://mdeabreu.com

# Permalinks
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Category Archive
category_archive:
  path: "category"

# Tag Archive
tag_archive:
  path: "tag"

# Excerpts
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
destination: ../../public
