# General Configuration
pygments: true
destination: ../public
markdown: kramdown

# Permalink
permalink: /:year/:month/:day/:title/

# Site
title: Matthew DeAbreu
tagline: 
url: http://mdeabreu.com

# Author
author:
  name: Matthew DeAbreu
  url: http://mdeabreu.com

# Paginate
paginate: 10

# Excerpts
excerpt_separator: <!--more-->
